export const projects = [
	{
		name: "Twoje Nieruchomości",
		link: "https://nieruchomosci.vercel.app/",
		githubLink: "https://github.com/konrad-jankowski/real-estate-app",
		category: "real-estate",
		featuredImg: "/projects/real-estate/featured.png",
		responsibility: ["develop", "design"],
		dateOfBuild: 2024,
	},
	{
		name: "Razer E-commerce",
		link: "https://razer-store-ten.vercel.app/",
		githubLink: "https://github.com/konrad-jankowski/razer-store.git",
		category: "e-commerce",
		featuredImg: "/projects/razer-store/featured.png",
		responsibility: ["develop"],
		dateOfBuild: 2023,
	},
	{
		name: "Levarde",
		link: "https://levarde.com/",
		category: "e-commerce",
		featuredImg: "/projects/levarde/featured.png",
		responsibility: ["develop", "design"],
		dateOfBuild: 2023,
		githubLink: "",
	},
	{
		name: "Fajne chatki",
		link: "https://cool-houses.vercel.app/",
		githubLink: "https://github.com/konrad-jankowski/cool-houses.git",
		category: "landing-page",
		featuredImg: "/projects/cool-houses/featured.png",
		responsibility: ["develop"],
		dateOfBuild: 2023,
	},
	{
		name: "Fox-dev",
		link: "https://fox-dev-eight.vercel.app",
		githubLink: "https://github.com/konrad-jankowski/FoxDev",
		category: "agency-website",
		featuredImg: "/projects/fox-dev/featured.png",
		responsibility: ["develop", "design"],
		dateOfBuild: 2024,
	},
	{
		name: "Sizer 2.0",
		link: "https://sizer-2-0.vercel.app",
		githubLink: "https://github.com/konrad-jankowski/Sizer-2.0",
		category: "e-commerce",
		featuredImg: "/projects/sizer2.0/featured.png",
		responsibility: ["develop"],
		dateOfBuild: 2022,
	},
];
